### ISSUE TITLE
NVIM config in Readme

### ISSUE THREAD

**Issue by vanguard-bit** [tekumara/typos-vscode#29]
typos-vscode is the only listed netrw lsp for nvim in Mason ....so the configuration for don't really know lua in readme is gonna be useful
Thanks!

**Comment by tekumara** [comment]
Hiya I'm not too familar with nvim, does the [config mentioned here](https://github.com/tekumara/typos-vscode?tab=readme-ov-file#install) not work for you"?

**Comment by tekumara** [comment]
Hiya I'm not too familar with nvim, does the [config mentioned here](https://github.com/tekumara/typos-vscode?tab=readme-ov-file#install) not work for you?

**Comment by YDX-2147483647** [comment]
I refer to https://github.com/neovim/nvim-lspconfig/blob/f5dab1398b12f1c96c5b185f802e3065f355b4a8/doc/server_configurations.md#typos_lsp and add the following to my `init.lua`. It works.

```lua
local lspconfig = require('lspconfig')
lspconfig.typos_lsp.setup{}
```

To debug, you can open a file and run `:LspInfo`.

By the way, the workspace should [has `typos.toml`, `_typos.toml`, or `.typos.toml`](https://github.com/neovim/nvim-lspconfig/blob/f5dab1398b12f1c96c5b185f802e3065f355b4a8/lua/lspconfig/server_configurations/typos_lsp.lua#L7). Otherwise, `root_dir` can't be determined, therefore typos is not enabled. If you want to always enable, the following might work.

```lua
lspconfig.typos_lsp.setup{
  root_dir = function(fname)
    return require('lspconfig.util').root_pattern('typos.toml', '_typos.toml', '.typos.toml')(fname)
      or vim.fn.getcwd()
  end,
}
```

**Comment by vanguard-bit** [comment]
I actually used the setup from nvim lsp-config....but it didn't get attached to buffer....i should try what you suggested....and i always have problem setting up root directory for all the lsps

**Comment by tekumara** [comment]
Did that work for you @vanguard-bit ?

**Comment by tekumara** [comment]
Thanks @YDX-2147483647 ! Did that work for you @vanguard-bit ?

**Comment by vanguard-bit** [comment]
yep it works now
Thanks @tekumara and @YDX-2147483647

**Comment by dmtrKovalenko** [comment]
Somehow setting up the root_dir made my config to fail on every save, for some reason specifically in lua files. Sending it here maybe someone is also looking for the root of the problem

```   Error  18:27:27 msg_show.lua_error Error detected while processing BufWritePost Autocommands for "<buffer=3>":
18:27:27 msg_show Error executing lua callback: ....10.0/share/nvim/runtime/lua/vim/lsp/_changetracking.lua:175: attempt to index local 'buf_state' (a nil value)
stack traceback:
	....10.0/share/nvim/runtime/lua/vim/lsp/_changetracking.lua:175: in function '_get_and_set_name'
	.../Cellar/neovim/0.10.0/share/nvim/runtime/lua/vim/lsp.lua:465: in function 'text_document_did_save_handler'
	.../Cellar/neovim/0.10.0/share/nvim/runtime/lua/vim/lsp.lua:543: in function <.../Cellar/neovim/0.10.0/share/nvim/runtime/lua/vim/lsp.lua:542>
)```
